VERSION-1.3
ATTENTION - SUR LA PAGES COMMANDES -Erreur de type Exception report

messageInternal Server Error

descriptionThe server encountered an internal error that prevented it
from fulfilling this request.

exception

javax.servlet.ServletException: could not execute query
root cause

org.hibernate.exception.GenericJDBCException: could not execute query
root cause

java.sql.SQLException: Value '0000-00-00 00:00:00' can not be
represented as java.sql.Timestamp
note The full stack traces of the exception and its root causes are
available in the GlassFish Server Open Source Edition 4.1 logs.